# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 11:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pipeline.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=8)),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=8)),
                ('is_damaged', models.BooleanField(default=False)),
                ('damage_grade', models.CharField(default='B', max_length=2)),
                ('image', models.ImageField(blank=True, null=True, upload_to=pipeline.models.upload_location)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
