# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='latitude',
            field=models.DecimalField(decimal_places=3, max_digits=100),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='longitude',
            field=models.DecimalField(decimal_places=3, max_digits=100),
        ),
    ]
