# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0002_auto_20180515_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='damage_grade',
            field=models.CharField(choices=[(b'0', b'None'), (b'1', b'Light'), (b'2', b'severe'), (b'3', b'Devastating')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='is_damaged',
            field=models.CharField(choices=[(b'L', b'lEAKING'), (b'O', b'OK')], default='O', max_length=2),
        ),
    ]
