# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-17 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0003_auto_20180515_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='damage_grade',
            field=models.CharField(choices=[(b'None', b'None'), (b'Light', b'Light'), (b'severe', b'severe'), (b'Devastating', b'Devastating')], default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='is_damaged',
            field=models.CharField(choices=[(b'LEAKING', b'LEAKING'), (b'NOT LEAKING', b'NOT LEAKING')], default='NOT Leaking', max_length=10),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=100),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=100),
        ),
    ]
